name: Docker Image CI

on:
  push:
    branches:
      - 'refs/tags/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get tag
        id: tagName
        uses: olegtarasov/get-tag@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./cdk8s
          file: ./cdk8s/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.gitlab.com/andcan/images/argocd/cdk8s:${{steps.tagName.outputs.tag}}
          build-args: |
            ARGOCD_VERSION=v1.7.8
            CDK8S_VERSION=v0.33.0